# Generated by Django 5.2.1 on 2025-05-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorychunk',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
